import { CameraSpec, MaterialSpec, SolvedScene } from "./types.js";

/**
 * Backend adapter: solved scene → Blender Python.
 *
 * This is the only file in the solve layer that knows Blender exists. The
 * solver produces plain numbers, so swapping the executor — authoring USD
 * prims directly, emitting three.js for a live preview, driving a different
 * DCC — means writing a sibling of this file, not touching the language
 * authors write in. That is what "engine-agnostic" has to mean concretely:
 * the relations are portable, the emitter is disposable.
 *
 * The emitted script is deterministic: parts come out in the solver's sorted
 * order and every number is fixed-precision, so an unchanged spec produces a
 * byte-identical script and the pipeline's content-hash cache hits.
 *
 * Every shape is authored to fill its solved box exactly — the same AABB
 * semantics the solver reasoned with — by creating a unit primitive,
 * rotating it onto its axis, applying the rotation, then scaling to the box
 * and applying the scale. Applying both transforms is deliberate: the
 * census sees identity transforms and clean world-space geometry, so the
 * unapplied-scale and non-uniform-scale rules can never fire on generated
 * output. The one exception is the torus, whose ring/tube radii are not a
 * uniform scale of a unit torus, so it is authored at its real radii.
 */
export interface EmitOptions {
  /** false suppresses the camera entirely; a CameraSpec steers the framing. */
  camera?: boolean | CameraSpec;
  lights?: boolean;
  /** Lighting style: derived studio key (default) or an outdoor sun. */
  light?: "studio" | "sun";
  /** Named material definitions from the spec's `materials` block. */
  materials?: Record<string, MaterialSpec>;
}

export function emitBlenderScript(scene: SolvedScene, options: EmitOptions = {}): string {
  const lines: string[] = [
    "# Generated by @open-design/scene3d from a declarative scene spec.",
    "# Do not hand-edit: edit scene.json and recompile. Coordinates here are",
    "# solved output, not authored input — the relations are the source.",
    "import bpy, math",
    "",
    "_materials = {}",
    "",
    "",
    "def _material(name):",
    '    """One Principled material per name, authored entirely from the',
    "    spec's materials block — a spec-built scene can never contain an",
    '    untouched default material."""',
    "    if name in _materials:",
    "        return _materials[name]",
    "    mat = bpy.data.materials.new(name)",
    "    mat.use_nodes = True",
    '    bsdf = mat.node_tree.nodes["Principled BSDF"]',
    "    spec = _MATERIAL_SPECS.get(name)",
    "    if spec is not None:",
    '        bsdf.inputs["Base Color"].default_value = spec["base_color"]',
    '        bsdf.inputs["Roughness"].default_value = spec["roughness"]',
    '        bsdf.inputs["Metallic"].default_value = spec["metallic"]',
    '        if spec.get("emission") is not None:',
    '            bsdf.inputs["Emission Color"].default_value = spec["emission"]',
    "        # Strength is applied whether or not a COLOUR was declared. A",
    "        # material lit by a baked emission map declares the strength and",
    "        # gets its colour from the texture, and gating both on the colour",
    "        # meant `emissionStrength: 4` was read, carried through the spec,",
    "        # and then dropped on the floor — leaving Blender's default of 0,",
    "        # which is a surface that emits nothing. The atelier's lava orb",
    "        # declared 4 and had never once glowed.",
    '        if spec.get("emission") is not None or spec.get("emission_strength") is not None:',
    "        # .get with a default, not [\"...\"]: the two keys are written together",
    "        # today, but this script is DATA that a cache can hand back from an",
    "        # older writer, and a KeyError here kills the Blender job with a",
    "        # traceback instead of a diagnostic.",
    '            bsdf.inputs["Emission Strength"].default_value = spec.get("emission_strength", 1.0)',
    '        if spec.get("alpha") is not None and spec["alpha"] < 1.0:',
    '            bsdf.inputs["Alpha"].default_value = spec["alpha"]',
    "            # EEVEE Next names it surface_render_method; legacy EEVEE",
    "            # names it blend_method. Set whichever this Blender has.",
    '            if hasattr(mat, "surface_render_method"):',
    '                mat.surface_render_method = "BLENDED"',
    '            elif hasattr(mat, "blend_method"):',
    '                mat.blend_method = "BLEND"',
    "    _materials[name] = mat",
    "    return mat",
    "",
    "",
    "_AXIS_ROT = {",
    '    "z": None,',
    "    # Local z onto world x / world y; symmetric shapes make sign moot.",
    '    "x": (0.0, math.pi / 2, 0.0),',
    '    "y": (math.pi / 2, 0.0, 0.0),',
    "}",
    "",
    "",
    "def _part(name, shape, size, center, axis, flip, material=None):",
    '    """Author a part filling its solved box exactly. Rotation and scale',
    "    are applied immediately so the exported transform is identity and",
    '    the transform-hygiene rules stay quiet by construction."""',
    '    if shape == "box":',
    "        bpy.ops.mesh.primitive_cube_add(size=1.0, location=center)",
    '    elif shape == "cylinder":',
    "        # TRIFAN caps: an ngon cap would trip the ngon rule on every",
    "        # column — generated output must lint clean by construction.",
    '        bpy.ops.mesh.primitive_cylinder_add(vertices=48, radius=0.5, depth=1.0, end_fill_type="TRIFAN", location=center)',
    '    elif shape == "sphere":',
    "        bpy.ops.mesh.primitive_uv_sphere_add(segments=48, ring_count=24, radius=0.5, location=center)",
    '    elif shape == "cone":',
    '        bpy.ops.mesh.primitive_cone_add(vertices=48, radius1=0.5, radius2=0.0, depth=1.0, end_fill_type="TRIFAN", location=center)',
    '    elif shape == "torus":',
    "        # size is (ring, ring, tube) in axis-local terms; radii are real,",
    "        # not a unit scale, because ring and tube scale independently.",
    "        _sizes = {axis_name: size[i] for i, axis_name in enumerate((\"x\", \"y\", \"z\"))}",
    "        tube = _sizes[axis] / 2.0",
    '        across = [v for k, v in _sizes.items() if k != axis][0]',
    "        bpy.ops.mesh.primitive_torus_add(",
    "            major_radius=across / 2.0 - tube, minor_radius=tube,",
    "            major_segments=48, minor_segments=24, location=center)",
    "    else:",
    '        raise ValueError("unknown shape: %s" % shape)',
    "    obj = bpy.context.object",
    "    obj.name = name",
    "    rot = _AXIS_ROT[axis]",
    "    if flip:",
    "        obj.rotation_euler = (math.pi, 0.0, 0.0)",
    "        bpy.ops.object.transform_apply(location=False, rotation=True, scale=False)",
    "    if rot is not None:",
    "        obj.rotation_euler = rot",
    "        bpy.ops.object.transform_apply(location=False, rotation=True, scale=False)",
    '    if shape != "torus":',
    "        obj.scale = size",
    "        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)",
    '    if shape in ("sphere", "torus"):',
    "        bpy.ops.object.shade_smooth()",
    "    if material:",
    "        obj.data.materials.append(_material(material))",
    "    return obj",
    "",
    "",
    "def _animate_spin(name, axis_index, period_frames):",
    '    """One full turn per period, linear, looped forever via the cycles',
    '    modifier — the compiler owns the keyframes, the author owns intent."""',
    "    obj = bpy.data.objects[name]",
    "    obj.rotation_mode = \"XYZ\"",
    "    obj.keyframe_insert(\"rotation_euler\", frame=1)",
    "    obj.rotation_euler[axis_index] = 6.283185307179586",
    "    obj.keyframe_insert(\"rotation_euler\", frame=1 + period_frames)",
    "    obj.rotation_euler[axis_index] = 0.0",
    "    _loop_fcurves(obj, \"rotation_euler\", linear=True)",
    "",
    "",
    "def _animate_bob(name, amplitude, period_frames):",
    '    """Vertical sine bob around the solved position, looped."""',
    "    obj = bpy.data.objects[name]",
    "    base_z = obj.location.z",
    "    quarter = max(1, period_frames // 4)",
    "    for step, offset in enumerate((0.0, amplitude, 0.0, -amplitude, 0.0)):",
    "        obj.location.z = base_z + offset",
    "        obj.keyframe_insert(\"location\", index=2, frame=1 + step * quarter)",
    "    obj.location.z = base_z",
    "    _loop_fcurves(obj, \"location\", linear=False)",
    "",
    "",
    "def _loop_fcurves(obj, data_path, linear):",
    "    action = obj.animation_data.action if obj.animation_data else None",
    "    if action is None:",
    "        return",
    "    try:",
    "        curves = list(action.fcurves)",
    "    except AttributeError:",
    "        # Blender 5 layered actions",
    "        curves = [fc for layer in action.layers for strip in layer.strips",
    "                  for bag in strip.channelbags for fc in bag.fcurves]",
    "    for fc in curves:",
    "        if fc.data_path != data_path:",
    "            continue",
    "        if linear:",
    "            for kp in fc.keyframe_points:",
    "                kp.interpolation = \"LINEAR\"",
    "        fc.modifiers.new(\"CYCLES\")",
    "",
    "",
    "def _import_part(name, filepath, size, center, material=None):",
    '    """Fill a solved box with a REAL asset: import, join its meshes into',
    "    one named part, drop non-mesh scaffolding it carried, and fit it",
    "    INSIDE the box — uniform scale, centred on x/y, resting on the box's",
    "    bottom — so relations behave exactly as for primitives. The asset's",
    '    own materials and textures are kept untouched."""',
    "    from mathutils import Vector",
    "    before = set(o.name for o in bpy.data.objects)",
    "    ext = filepath.rsplit(\".\", 1)[-1].lower()",
    '    if ext in ("glb", "gltf"):',
    "        bpy.ops.import_scene.gltf(filepath=filepath)",
    '    elif ext == "obj":',
    "        bpy.ops.wm.obj_import(filepath=filepath)",
    '    elif ext == "fbx":',
    "        bpy.ops.import_scene.fbx(filepath=filepath)",
    "    else:",
    '        raise ValueError("unsupported asset: %s" % filepath)',
    "    imported = [o for o in bpy.data.objects if o.name not in before]",
    '    meshes = [o for o in imported if o.type == "MESH"]',
    "    if not meshes:",
    '        raise ValueError("no mesh objects in %s" % filepath)',
    "    # Static placement: unparent meshes (keeping their world transform),",
    "    # strip rig modifiers, and remove imported cameras/lights/empties —",
    "    # a part is geometry, not a stowaway scene.",
    "    for o in meshes:",
    "        mw = o.matrix_world.copy()",
    "        o.parent = None",
    "        o.matrix_world = mw",
    "        for mod in list(o.modifiers):",
    '            if mod.type == "ARMATURE":',
    "                o.modifiers.remove(mod)",
    "    for o in imported:",
    '        if o.type != "MESH":',
    "            bpy.data.objects.remove(o, do_unlink=True)",
    "    bpy.ops.object.select_all(action=\"DESELECT\")",
    "    mesh_names = [o.name for o in meshes]",
    "    for o in meshes:",
    "        try:",
    "            o.select_set(True)",
    "        except RuntimeError:",
    "            # Not in the view layer (importer scaffolding like bone",
    "            # custom-shape meshes); join cannot absorb it — the sweep",
    "            # below removes it by name instead.",
    "            pass",
    "    bpy.context.view_layer.objects.active = meshes[0]",
    "    if len(meshes) > 1:",
    "        bpy.ops.object.join()",
    "    obj = bpy.context.view_layer.objects.active",
    "    obj.name = name",
    "    # Sweep any imported mesh the join did not absorb: rig visualisation",
    "    # icospheres and other importer scaffolding must not become parts.",
    "    for nm in mesh_names:",
    "        stray = bpy.data.objects.get(nm)",
    "        if stray is not None and stray != obj:",
    "            bpy.data.objects.remove(stray, do_unlink=True)",
    "    # Bake whatever transform the importer authored, then fit the box.",
    "    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)",
    "    bpy.context.view_layer.update()",
    "    corners = [obj.matrix_world @ Vector(c) for c in obj.bound_box]",
    "    lo = [min(c[i] for c in corners) for i in range(3)]",
    "    hi = [max(c[i] for c in corners) for i in range(3)]",
    "    dim = [max(hi[i] - lo[i], 1e-9) for i in range(3)]",
    "    s = min(size[i] / dim[i] for i in range(3))",
    "    obj.scale = (obj.scale[0] * s, obj.scale[1] * s, obj.scale[2] * s)",
    "    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)",
    "    bpy.context.view_layer.update()",
    "    corners = [obj.matrix_world @ Vector(c) for c in obj.bound_box]",
    "    lo = [min(c[i] for c in corners) for i in range(3)]",
    "    hi = [max(c[i] for c in corners) for i in range(3)]",
    "    obj.location = (",
    "        obj.location[0] + center[0] - (lo[0] + hi[0]) / 2.0,",
    "        obj.location[1] + center[1] - (lo[1] + hi[1]) / 2.0,",
    "        obj.location[2] + (center[2] - size[2] / 2.0) - lo[2],",
    "    )",
    "    bpy.context.view_layer.update()",
    "    if material:",
    "        # Deliberate override: replace the asset's own materials.",
    "        obj.data.materials.clear()",
    "        obj.data.materials.append(_material(material))",
    "    return obj",
    "",
  ];

  /* ---- material table --------------------------------------------- */
  const referenced = [...new Set(scene.parts.map((p) => p.material).filter(Boolean))] as string[];
  lines.push("_MATERIAL_SPECS = {");
  for (const name of referenced.sort()) {
    const spec = options.materials?.[name];
    if (spec) {
      // A shader material has no authored base colour — the bake owns the
      // surface. Neutral grey placeholder until the runner wires textures.
      const base = spec.baseColor ?? [0.8, 0.8, 0.8];
      const entries = [
        `"base_color": (${[...base, spec.alpha ?? 1].map(num).join(", ")})`,
        `"roughness": ${num(spec.roughness ?? 0.5)}`,
        `"metallic": ${num(spec.metallic ?? 0)}`,
      ];
      if (spec.emission) {
        entries.push(`"emission": (${[...spec.emission, 1].map(num).join(", ")})`);
      }
      // Strength travels whenever the author asked for emission by EITHER
      // means. It used to ride along with the colour, so a material lit by a
      // baked emission map — which declares a strength and takes its colour
      // from the texture — never emitted the key at all, and its declared
      // value was dropped between the spec and the build script. Absent when
      // neither is declared, so a plain material is not made to glow.
      if (spec.emission || spec.emissionStrength !== undefined) {
        entries.push(`"emission_strength": ${num(spec.emissionStrength ?? 1)}`);
      }
      if (spec.alpha !== undefined && spec.alpha < 1) {
        entries.push(`"alpha": ${num(spec.alpha)}`);
      }
      lines.push(`    ${py(name)}: {${entries.join(", ")}},`);
    } else {
      // A referenced-but-undeclared material still gets deliberate, visibly
      // placeholder values — never Blender's untouched defaults.
      lines.push(
        `    ${py(name)}: {"base_color": (0.55, 0.35, 0.15, 1.0), "roughness": 0.7, "metallic": 0.0},`,
      );
    }
  }
  lines.push("}", "");

  /* ---- parts ------------------------------------------------------- */
  for (const part of scene.parts) {
    const size = `(${part.size.map(num).join(", ")})`;
    const center = `(${part.center.map(num).join(", ")})`;
    const material = part.material ? `, ${py(part.material)}` : "";
    if (part.file !== undefined) {
      lines.push(`_import_part(${py(part.id)}, ${py(part.file)}, ${size}, ${center}${material})`);
    } else {
      lines.push(
        `_part(${py(part.id)}, ${py(part.shape)}, ${size}, ${center}, ${py(part.axis)}, ${part.flip ? "True" : "False"}${material})`,
      );
    }
  }
  lines.push("");

  /* ---- animation ---------------------------------------------------- */
  // Declarative motion, compiler-owned keyframes at 24fps. The scene's
  // frame range covers the longest single cycle; every curve loops via a
  // cycles modifier, so any playhead position is valid.
  const FPS = 24;
  const animated = scene.parts.filter((p) => p.spin || p.bob);
  if (animated.length > 0) {
    let maxFrames = 0;
    for (const part of animated) {
      if (part.spin) {
        const frames = Math.max(2, Math.round((part.spin.seconds ?? 4) * FPS));
        maxFrames = Math.max(maxFrames, frames);
        const axisIndex = { x: 0, y: 1, z: 2 }[part.spin.axis ?? "z"];
        lines.push(`_animate_spin(${py(part.id)}, ${axisIndex}, ${frames})`);
      }
      if (part.bob) {
        const frames = Math.max(4, Math.round((part.bob.seconds ?? 3) * FPS));
        maxFrames = Math.max(maxFrames, frames);
        lines.push(`_animate_bob(${py(part.id)}, ${num(part.bob.amplitude)}, ${frames})`);
      }
    }
    lines.push(
      `bpy.context.scene.frame_end = ${1 + maxFrames}`,
      "bpy.context.scene.frame_set(1)",
      "",
    );
  }

  /* ---- camera ------------------------------------------------------ */
  if (options.camera !== false) {
    const spec = typeof options.camera === "object" ? options.camera : {};
    const framing = frameScene(scene, spec);
    lines.push(
      "# Hero camera framed from the solved bounds — derived, not guessed.",
      `bpy.ops.object.camera_add(location=(${framing.location.map(num).join(", ")}))`,
      "cam = bpy.context.object",
      'cam.name = "cam_hero"',
      `cam.rotation_euler = (${framing.rotation.map(num).join(", ")})`,
      "bpy.context.scene.camera = cam",
      "",
    );
  }

  /* ---- lights ------------------------------------------------------ */
  if (options.lights !== false) {
    const framing = frameScene(scene, typeof options.camera === "object" ? options.camera : {});
    if (options.light === "sun") {
      lines.push(
        "# Outdoor sun: parallel light, so energy is irradiance and does not",
        "# need to scale with the subject.",
        `bpy.ops.object.light_add(type="SUN", location=(${num(framing.center[0] + framing.radius)}, ${num(framing.center[1] - framing.radius)}, ${num(framing.center[2] + framing.radius * 2)}))`,
        "key = bpy.context.object",
        'key.name = "lgt_key"',
        "key.data.energy = 3.0",
        "key.rotation_euler = (0.6, 0.2, 0.8)",
        "",
      );
    } else {
      const key = framing.radius * 2.5;
      lines.push(
        "# Key light scaled to the subject so exposure does not depend on how",
        "# large the model happens to be.",
        "#",
        "# Power goes as radius SQUARED, and neither term is floored. Both of",
        "# those were wrong before and in the same direction: the lamp sat at",
        "# a distance proportional to the radius, so irradiance falls as",
        "# radius^2, while power rose only linearly — leaving the subject lit",
        "# as 1/radius. Small subjects were therefore lit HARDER, exactly",
        "# inverting the promise this comment makes. The floors then finished",
        "# the job: a 1m minimum lamp physically envelops anything under half",
        "# a metre. Every prop, printed part, product shot and miniature",
        "# rendered pure white, and the proof reported the frame as EMPTY",
        "# rather than blown, sending the reader after a framing bug that was",
        "# not there.",
        "#",
        "# Squared power makes irradiance constant, so one calibration holds",
        "# at every scale: 4000W at a 1m radius, which is what the sizes that",
        "# always looked right were already getting.",
        `bpy.ops.object.light_add(type="AREA", location=(${num(framing.center[0] + key)}, ${num(framing.center[1] - key)}, ${num(framing.center[2] + key)}))`,
        "key = bpy.context.object",
        'key.name = "lgt_key"',
        `key.data.energy = ${num(KEY_WATTS_AT_ONE_METRE * framing.radius * framing.radius)}`,
        `key.data.size = ${num(framing.radius * 2)}`,
        "",
      );
    }
  }

  return lines.join("\n");
}

/**
 * Key-light power for a subject of one metre radius, in watts. Every other
 * size scales from here by radius squared, which is what keeps the subject's
 * illumination — not the lamp's number — the thing that stays constant.
 */
const KEY_WATTS_AT_ONE_METRE = 4000;

/**
 * Camera placement derived from the solved bounding box.
 *
 * Framing is arithmetic on numbers the solver already produced, so it does
 * not need a model call and cannot drift from the geometry: the shot always
 * contains the subject, at any scale, without anyone typing a distance. The
 * optional spec steers the derivation (orbit angle, elevation, distance in
 * bounding radii) without ever replacing it with absolute coordinates.
 */
export function frameScene(
  scene: SolvedScene,
  spec: CameraSpec = {},
): {
  center: [number, number, number];
  radius: number;
  location: [number, number, number];
  rotation: [number, number, number];
} {
  if (scene.parts.length === 0) {
    return { center: [0, 0, 0], radius: 1, location: [4, -4, 3], rotation: [1.1, 0, 0.785] };
  }
  const lo: [number, number, number] = [Infinity, Infinity, Infinity];
  const hi: [number, number, number] = [-Infinity, -Infinity, -Infinity];
  for (const part of scene.parts) {
    for (let axis = 0; axis < 3; axis++) {
      const half = part.size[axis]! / 2;
      lo[axis] = Math.min(lo[axis]!, part.center[axis]! - half);
      hi[axis] = Math.max(hi[axis]!, part.center[axis]! + half);
    }
  }
  const center: [number, number, number] = [
    (lo[0]! + hi[0]!) / 2,
    (lo[1]! + hi[1]!) / 2,
    (lo[2]! + hi[2]!) / 2,
  ];
  const radius =
    Math.hypot(hi[0]! - lo[0]!, hi[1]! - lo[1]!, hi[2]! - lo[2]!) / 2 || 1;
  // Defaults give a three-quarter view at 30° elevation: the angle that
  // reads a box as a box.
  const azimuth = ((spec.azimuthDeg ?? 45) * Math.PI) / 180;
  const elevation = ((spec.elevationDeg ?? 30) * Math.PI) / 180;
  const distance = radius * (spec.distance ?? 3.2);
  const location: [number, number, number] = [
    center[0] + distance * Math.cos(elevation) * Math.sin(azimuth),
    center[1] - distance * Math.cos(elevation) * Math.cos(azimuth),
    center[2] + distance * Math.sin(elevation),
  ];
  // Blender cameras look down local -Z; pitch down from level by elevation.
  const rotation: [number, number, number] = [Math.PI / 2 - elevation, 0, azimuth];
  return { center, radius, location, rotation };
}

/** Fixed precision keeps the emitted script byte-stable for the cache. */
function num(value: number): string {
  const rounded = Number(value.toFixed(6));
  return Object.is(rounded, -0) ? "0" : String(rounded);
}

function py(value: string): string {
  // Belt and braces under the validator's charset gates: even if a string
  // with control characters ever reached here, it must emit as a legal
  // single-line Python literal, never as a SyntaxError inside the
  // generated script.
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    // eslint-disable-next-line no-control-regex
    .replace(/[\x00-\x1f\x7f]/g, (ch) => `\\x${ch.charCodeAt(0).toString(16).padStart(2, "0")}`);
  return `"${escaped}"`;
}
