import { build } from "esbuild";
import { writeFileSync, readFileSync } from "node:fs";

/*
 * Step 1 — bundle the viewer math for the browser runtime.
 *
 * The kit page ships as one self-contained HTML string, so it cannot import
 * modules at runtime. To let the gizmo run the SAME code the Node test suite
 * covers (instead of an inline re-implementation that drifts from it), we
 * bundle src/viewer/math/ as an IIFE that exposes a single `S3DMath` global
 * and emit it as a string constant the renderer inlines into the page.
 *
 * The result is written to a committed generated file rather than left in
 * memory so that `tsc` / editor tooling can resolve the import without a build
 * having run first. It is regenerated on every build; if the bundle changed,
 * commit the diff (same discipline as a lockfile).
 */
const mathBundle = await build({
  bundle: true,
  entryPoints: ["./src/viewer/math/index.ts"],
  format: "iife",
  globalName: "S3DMath",
  platform: "browser",
  target: "es2020",
  minify: true,
  legalComments: "none",
  write: false,
});
const mathCode = mathBundle.outputFiles[0].text.trim();
const generated =
  "// AUTO-GENERATED by esbuild.config.mjs from src/viewer/math/. Do not edit by hand.\n" +
  "//\n" +
  "// The viewer's math engine, bundled as an IIFE that exposes the `S3DMath`\n" +
  "// global, inlined into the kit page so the gizmo runs the exact code the\n" +
  "// Node suite tests. Regenerated on every build; commit the diff if it moves.\n" +
  "export const KIT_MATH_JS = " +
  JSON.stringify(mathCode) +
  ";\n";
const target = "./src/viewer/kit-math.generated.ts";
// Only rewrite when the content actually changed, so a no-op build does not
// churn the file's mtime (and does not fight a concurrent editor).
let prev = "";
try {
  prev = readFileSync(target, "utf8");
} catch {
  /* first build */
}
if (prev !== generated) writeFileSync(target, generated);

/* Step 2 — bundle the package entry for Node (unchanged). */
await build({
  bundle: true,
  entryPoints: ["./src/index.ts"],
  format: "esm",
  outfile: "./dist/index.mjs",
  packages: "external",
  platform: "node",
  target: "node24",
});

/*
 * Step 3 — bundle the off-thread compile worker, beside the index.
 *
 * `compileInWorker` runs the whole compile on a worker thread so a CPU-heavy
 * exact-rational evaluation never stalls the caller's event loop. The worker is
 * its own bundled entry (a separate thread is a separate module instance, so
 * the duplicated bundle is fine) and resolves relative to dist/index.mjs via
 * `new URL('./compile-worker.mjs', import.meta.url)`.
 */
await build({
  bundle: true,
  entryPoints: ["./src/compile-worker.ts"],
  format: "esm",
  outfile: "./dist/compile-worker.mjs",
  packages: "external",
  platform: "node",
  target: "node24",
});
