# Generated by @open-design/scene3d from a declarative scene spec.
# Do not hand-edit: edit scene.json and recompile. Coordinates here are
# solved output, not authored input — the relations are the source.
import bpy, math

_materials = {}


def _material(name):
    """One Principled material per name, authored entirely from the
    spec's materials block — a spec-built scene can never contain an
    untouched default material."""
    if name in _materials:
        return _materials[name]
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes["Principled BSDF"]
    spec = _MATERIAL_SPECS.get(name)
    if spec is not None:
        bsdf.inputs["Base Color"].default_value = spec["base_color"]
        bsdf.inputs["Roughness"].default_value = spec["roughness"]
        bsdf.inputs["Metallic"].default_value = spec["metallic"]
        if spec.get("emission") is not None:
            bsdf.inputs["Emission Color"].default_value = spec["emission"]
            bsdf.inputs["Emission Strength"].default_value = spec["emission_strength"]
        if spec.get("alpha") is not None and spec["alpha"] < 1.0:
            bsdf.inputs["Alpha"].default_value = spec["alpha"]
            # EEVEE Next names it surface_render_method; legacy EEVEE
            # names it blend_method. Set whichever this Blender has.
            if hasattr(mat, "surface_render_method"):
                mat.surface_render_method = "BLENDED"
            elif hasattr(mat, "blend_method"):
                mat.blend_method = "BLEND"
    _materials[name] = mat
    return mat


_AXIS_ROT = {
    "z": None,
    # Local z onto world x / world y; symmetric shapes make sign moot.
    "x": (0.0, math.pi / 2, 0.0),
    "y": (math.pi / 2, 0.0, 0.0),
}


def _part(name, shape, size, center, axis, flip, material=None):
    """Author a part filling its solved box exactly. Rotation and scale
    are applied immediately so the exported transform is identity and
    the transform-hygiene rules stay quiet by construction."""
    if shape == "box":
        bpy.ops.mesh.primitive_cube_add(size=1.0, location=center)
    elif shape == "cylinder":
        # TRIFAN caps: an ngon cap would trip the ngon rule on every
        # column — generated output must lint clean by construction.
        bpy.ops.mesh.primitive_cylinder_add(vertices=48, radius=0.5, depth=1.0, end_fill_type="TRIFAN", location=center)
    elif shape == "sphere":
        bpy.ops.mesh.primitive_uv_sphere_add(segments=48, ring_count=24, radius=0.5, location=center)
    elif shape == "cone":
        bpy.ops.mesh.primitive_cone_add(vertices=48, radius1=0.5, radius2=0.0, depth=1.0, end_fill_type="TRIFAN", location=center)
    elif shape == "torus":
        # size is (ring, ring, tube) in axis-local terms; radii are real,
        # not a unit scale, because ring and tube scale independently.
        _sizes = {axis_name: size[i] for i, axis_name in enumerate(("x", "y", "z"))}
        tube = _sizes[axis] / 2.0
        across = [v for k, v in _sizes.items() if k != axis][0]
        bpy.ops.mesh.primitive_torus_add(
            major_radius=across / 2.0 - tube, minor_radius=tube,
            major_segments=48, minor_segments=24, location=center)
    else:
        raise ValueError("unknown shape: %s" % shape)
    obj = bpy.context.object
    obj.name = name
    rot = _AXIS_ROT[axis]
    if flip:
        obj.rotation_euler = (math.pi, 0.0, 0.0)
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=False)
    if rot is not None:
        obj.rotation_euler = rot
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=False)
    if shape != "torus":
        obj.scale = size
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    if shape in ("sphere", "torus"):
        bpy.ops.object.shade_smooth()
    if material:
        obj.data.materials.append(_material(material))
    return obj


def _animate_spin(name, axis_index, period_frames):
    """One full turn per period, linear, looped forever via the cycles
    modifier — the compiler owns the keyframes, the author owns intent."""
    obj = bpy.data.objects[name]
    obj.rotation_mode = "XYZ"
    obj.keyframe_insert("rotation_euler", frame=1)
    obj.rotation_euler[axis_index] = 6.283185307179586
    obj.keyframe_insert("rotation_euler", frame=1 + period_frames)
    obj.rotation_euler[axis_index] = 0.0
    _loop_fcurves(obj, "rotation_euler", linear=True)


def _animate_bob(name, amplitude, period_frames):
    """Vertical sine bob around the solved position, looped."""
    obj = bpy.data.objects[name]
    base_z = obj.location.z
    quarter = max(1, period_frames // 4)
    for step, offset in enumerate((0.0, amplitude, 0.0, -amplitude, 0.0)):
        obj.location.z = base_z + offset
        obj.keyframe_insert("location", index=2, frame=1 + step * quarter)
    obj.location.z = base_z
    _loop_fcurves(obj, "location", linear=False)


def _loop_fcurves(obj, data_path, linear):
    action = obj.animation_data.action if obj.animation_data else None
    if action is None:
        return
    try:
        curves = list(action.fcurves)
    except AttributeError:
        # Blender 5 layered actions
        curves = [fc for layer in action.layers for strip in layer.strips
                  for bag in strip.channelbags for fc in bag.fcurves]
    for fc in curves:
        if fc.data_path != data_path:
            continue
        if linear:
            for kp in fc.keyframe_points:
                kp.interpolation = "LINEAR"
        fc.modifiers.new("CYCLES")


def _import_part(name, filepath, size, center, material=None):
    """Fill a solved box with a REAL asset: import, join its meshes into
    one named part, drop non-mesh scaffolding it carried, and fit it
    INSIDE the box — uniform scale, centred on x/y, resting on the box's
    bottom — so relations behave exactly as for primitives. The asset's
    own materials and textures are kept untouched."""
    from mathutils import Vector
    before = set(o.name for o in bpy.data.objects)
    ext = filepath.rsplit(".", 1)[-1].lower()
    if ext in ("glb", "gltf"):
        bpy.ops.import_scene.gltf(filepath=filepath)
    elif ext == "obj":
        bpy.ops.wm.obj_import(filepath=filepath)
    elif ext == "fbx":
        bpy.ops.import_scene.fbx(filepath=filepath)
    else:
        raise ValueError("unsupported asset: %s" % filepath)
    imported = [o for o in bpy.data.objects if o.name not in before]
    meshes = [o for o in imported if o.type == "MESH"]
    if not meshes:
        raise ValueError("no mesh objects in %s" % filepath)
    # Static placement: unparent meshes (keeping their world transform),
    # strip rig modifiers, and remove imported cameras/lights/empties —
    # a part is geometry, not a stowaway scene.
    for o in meshes:
        mw = o.matrix_world.copy()
        o.parent = None
        o.matrix_world = mw
        for mod in list(o.modifiers):
            if mod.type == "ARMATURE":
                o.modifiers.remove(mod)
    for o in imported:
        if o.type != "MESH":
            bpy.data.objects.remove(o, do_unlink=True)
    bpy.ops.object.select_all(action="DESELECT")
    mesh_names = [o.name for o in meshes]
    for o in meshes:
        try:
            o.select_set(True)
        except RuntimeError:
            # Not in the view layer (importer scaffolding like bone
            # custom-shape meshes); join cannot absorb it — the sweep
            # below removes it by name instead.
            pass
    bpy.context.view_layer.objects.active = meshes[0]
    if len(meshes) > 1:
        bpy.ops.object.join()
    obj = bpy.context.view_layer.objects.active
    obj.name = name
    # Sweep any imported mesh the join did not absorb: rig visualisation
    # icospheres and other importer scaffolding must not become parts.
    for nm in mesh_names:
        stray = bpy.data.objects.get(nm)
        if stray is not None and stray != obj:
            bpy.data.objects.remove(stray, do_unlink=True)
    # Bake whatever transform the importer authored, then fit the box.
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    bpy.context.view_layer.update()
    corners = [obj.matrix_world @ Vector(c) for c in obj.bound_box]
    lo = [min(c[i] for c in corners) for i in range(3)]
    hi = [max(c[i] for c in corners) for i in range(3)]
    dim = [max(hi[i] - lo[i], 1e-9) for i in range(3)]
    s = min(size[i] / dim[i] for i in range(3))
    obj.scale = (obj.scale[0] * s, obj.scale[1] * s, obj.scale[2] * s)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    bpy.context.view_layer.update()
    corners = [obj.matrix_world @ Vector(c) for c in obj.bound_box]
    lo = [min(c[i] for c in corners) for i in range(3)]
    hi = [max(c[i] for c in corners) for i in range(3)]
    obj.location = (
        obj.location[0] + center[0] - (lo[0] + hi[0]) / 2.0,
        obj.location[1] + center[1] - (lo[1] + hi[1]) / 2.0,
        obj.location[2] + (center[2] - size[2] / 2.0) - lo[2],
    )
    bpy.context.view_layer.update()
    if material:
        # Deliberate override: replace the asset's own materials.
        obj.data.materials.clear()
        obj.data.materials.append(_material(material))
    return obj

_MATERIAL_SPECS = {
    "mtl_rusted": {"base_color": (0.8, 0.8, 0.8, 1), "roughness": 0.5, "metallic": 0},
    "mtl_stone": {"base_color": (0.6, 0.6, 0.58, 1), "roughness": 0.9, "metallic": 0},
}

_part("prp_crate", "box", (0.8, 0.8, 0.8), (0, 0, 0.499), "z", False, "mtl_rusted")
_part("prp_slab", "box", (1.6, 1.6, 0.1), (0, 0, 0.05), "z", False, "mtl_stone")

# Hero camera framed from the solved bounds — derived, not guessed.
bpy.ops.object.camera_add(location=(2.385597, -2.385597, 2.397332))
cam = bpy.context.object
cam.name = "cam_hero"
cam.rotation_euler = (1.047198, 0, 0.785398)
bpy.context.scene.camera = cam

# Key light scaled to the subject so exposure does not depend on how
# large the model happens to be.
bpy.ops.object.light_add(type="AREA", location=(3.043487, -3.043487, 3.492987))
key = bpy.context.object
key.name = "lgt_key"
key.data.energy = 4869.579448
key.data.size = 2.43479
