import { chmod, mkdir, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import type { ToolDevConfig } from "./config.js";

export type DesktopLinkOptions = {
  path?: string;
};

export type DesktopLinkResult = {
  platform: NodeJS.Platform;
  path: string;
  written: "created" | "replaced";
  launchCommand: string;
};

const DEFAULT_LAUNCHER_FILENAME = "Open Design (Dev).command";

/**
 * The dev-runtime Desktop launcher is macOS-only, mirroring the Windows-only
 * `.lnk` shortcut electron-builder creates during `tools-pack win install`.
 * Other platforms have their own shortcut mechanisms (or none) and embedding a
 * `.command` there would be inert.
 */
function assertMacPlatform(platform: NodeJS.Platform): void {
  if (platform === "darwin") return;
  throw new Error(
    "tools-dev link is macOS-only; Windows shortcuts are created by tools-pack win install",
  );
}

function resolveLauncherPath(options: DesktopLinkOptions): string {
  if (options.path != null && options.path !== "") {
    return path.resolve(options.path);
  }
  return path.join(os.homedir(), "Desktop", DEFAULT_LAUNCHER_FILENAME);
}

/**
 * Absolute paths are baked in at generation time so a double-clicked
 * `.command` does not depend on `pnpm`/`corepack`/`node` being on the Finder
 * shell's PATH — the single largest real-world failure mode for these files.
 * It invokes the package `bin` entry directly with the resolved node binary.
 */
function buildLauncherScript(config: ToolDevConfig, nodePath: string): string {
  const toolsDevBin = path.join(config.workspaceRoot, "tools", "dev", "bin", "tools-dev.mjs");
  return [
    "#!/bin/bash",
    "# Generated by `tools-dev link`. Launches the Open Design dev runtime.",
    `NODE=${JSON.stringify(nodePath)}`,
    `TOOLS_DEV=${JSON.stringify(toolsDevBin)}`,
    'if [ ! -x "$NODE" ]; then',
    '  echo "Node binary not found at $NODE — regenerate with: pnpm tools-dev link" >&2',
    '  read -n 1 -s -r -p "Press any key to close."',
    "  exit 1",
    "fi",
    `cd ${JSON.stringify(config.workspaceRoot)} || exit 1`,
    `exec "$NODE" "$TOOLS_DEV" start --namespace ${JSON.stringify(config.namespace)}`,
    "",
  ].join("\n");
}

async function fileExists(target: string): Promise<boolean> {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
}

export async function createDesktopLink(
  config: ToolDevConfig,
  options: DesktopLinkOptions = {},
  deps: { platform?: NodeJS.Platform; nodePath?: string } = {},
): Promise<DesktopLinkResult> {
  const platform = deps.platform ?? process.platform;
  assertMacPlatform(platform);

  const launcherPath = resolveLauncherPath(options);
  const nodePath = deps.nodePath ?? process.execPath;
  const script = buildLauncherScript(config, nodePath);

  const existed = await fileExists(launcherPath);
  await mkdir(path.dirname(launcherPath), { recursive: true });
  await writeFile(launcherPath, script, "utf8");
  await chmod(launcherPath, 0o755);

  return {
    platform,
    path: launcherPath,
    written: existed ? "replaced" : "created",
    launchCommand: `${nodePath} ${path.join(config.workspaceRoot, "tools", "dev", "bin", "tools-dev.mjs")} start --namespace ${config.namespace}`,
  };
}
