// Adapter for OpenAI-family models served through Bedrock's Responses endpoint
// (`open-design-bedrock-openai`). Self-contained on purpose: deleting this file
// and its two call sites (buildBedrockFamilyProviderConfig, the run spawn in
// server.ts) removes the behaviour entirely.
//
// Why it exists. OpenCode's `read` tool returns a PDF as an attachment of the
// tool result. The AI SDK converts tool-result media without a filename, and
// its OpenAI Responses provider then sends `input_file` with
// `filename: "data"`. OpenAI infers the type from the data URL, Bedrock infers
// it from the filename, and rejects the request with
// `Unsupported file type: 'data'`. A PDF attached to a *user* message goes
// through a different SDK path that names it `part-N.pdf`, which Bedrock
// accepts (verified 2026-09-11 against bedrock-runtime, both directly and
// through the bundled OpenCode companion).
//
// So the plugin hooks `experimental.chat.messages.transform` (available in the
// bundled companion) and, before each model call, moves PDF attachments off
// the tool parts into a trailing synthetic user message carrying a named file
// part. The tool result keeps its text ("PDF read successfully"), the model
// still sees the document, and nothing is persisted: the hook only sees the
// in-memory copy used for the conversion.
//
// Remove once either side fixes the root cause: the AI SDK defaulting the
// tool-result filename by media type like it does for user parts, or Bedrock
// inferring the type from the data URL like OpenAI does.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

export const BEDROCK_OPENAI_FILE_ADAPTER_PLUGIN_FILENAME = 'bedrock-openai-file-adapter.js';

export const BEDROCK_OPENAI_FILE_ADAPTER_PLUGIN_SOURCE = `// Generated by Open Design (apps/daemon/src/runtimes/bedrock-openai-file-adapter.ts).
// Moves PDF attachments returned by tools into a named user file part so the
// Bedrock OpenAI Responses endpoint accepts them. Safe to delete; it is
// rewritten on the next run.
const DOCUMENT_MIMES = new Set(["application/pdf"]);

function isDocument(attachment) {
  const mime = String(attachment?.mime ?? "").split(";")[0].trim().toLowerCase();
  return attachment?.type === "file" && DOCUMENT_MIMES.has(mime);
}

export const BedrockOpenAIFileAdapter = async () => ({
  "experimental.chat.messages.transform": async (_input, output) => {
    const messages = output?.messages;
    if (!Array.isArray(messages) || messages.length === 0) return;
    const moved = [];
    for (const message of messages) {
      for (const part of message?.parts ?? []) {
        if (part?.type !== "tool" || !Array.isArray(part.state?.attachments)) continue;
        const documents = part.state.attachments.filter(isDocument);
        if (documents.length === 0) continue;
        part.state.attachments = part.state.attachments.filter((a) => !isDocument(a));
        for (const document of documents) moved.push({ document, part });
      }
    }
    if (moved.length === 0) return;
    // Attach to the most recent real user message: the converter is known to
    // forward its file parts (with filename) to the SDK.
    const target = [...messages].reverse().find((m) => m?.info?.role === "user" && Array.isArray(m.parts));
    if (!target) return;
    const sessionID = target.info.sessionID;
    const messageID = target.info.id;
    for (const [index, { document, part }] of moved.entries()) {
      target.parts.push({
        id: \`prt_od_bedrock_file_adapter_\${index}\`,
        sessionID,
        messageID,
        type: "file",
        mime: document.mime,
        url: document.url,
        filename: document.filename ?? \`\${String(part.state?.input?.filePath ?? "document").split("/").pop()}\`,
      });
    }
    if (process.env.OD_BEDROCK_FILE_ADAPTER_TRACE) {
      console.error(\`[bedrock-file-adapter] moved \${moved.length} document(s) onto user message \${messageID}\`);
    }
  },
});
`;

/**
 * Write the plugin under the daemon data dir (idempotent) and return the
 * `file://` URL OpenCode expects in `config.plugin`.
 */
export function ensureBedrockOpenAiFileAdapterPlugin(dataDir: string): string {
  const dir = path.join(dataDir, 'opencode-plugins');
  const file = path.join(dir, BEDROCK_OPENAI_FILE_ADAPTER_PLUGIN_FILENAME);
  let current: string | null = null;
  try {
    current = readFileSync(file, 'utf8');
  } catch {
    current = null;
  }
  if (current !== BEDROCK_OPENAI_FILE_ADAPTER_PLUGIN_SOURCE) {
    mkdirSync(dir, { recursive: true });
    writeFileSync(file, BEDROCK_OPENAI_FILE_ADAPTER_PLUGIN_SOURCE, 'utf8');
  }
  return pathToFileURL(file).href;
}
